Added custom contact
Collaborne/paper-contact pull request #6
Opened 2017-11-06 13:03 UTC by JaySunSyn

Thanks! :)

```
<paper-contact-custom icon="icons:favorite" no-link>Love it!</paper-contact-custom>
```

2017-11-06 15:06 UTC, ronnyroeller requested changes

2017-11-06 15:06 UTC, ronnyroeller commented on paper-contact-custom.html
> +Component for email contact details, that triggers the opening of the email client on tap.
Could you please adjust docu

2017-11-06 15:06 UTC, ronnyroeller commented on paper-contact-custom.html
> +        properties: {
Please double check indentation. It should be tabs (instead of spaces).

2017-11-06 15:06 UTC, ronnyroeller commented on paper-contact-custom.html
> +        _open: function() {
Please check indentation. It should be tabs (instead of spaces).

2017-11-06 17:59 UTC, JaySunSyn commented
I've added linter files. You can now run `npm run lint` which makes contribution easier..
Please adjust .eslintrc.json to your coding style if you decide to keep it.

2017-11-06 18:02 UTC, JaySunSyn commented
You could add a `.travis` file after `.eslintrc.json` adjusted. (to let the build process fail if test or linter fails)

Example for `.travis`:

```
language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install
  - polymer install
before_script:
  - npm run lint
script:
  - xvfb-run npm run test
  - xvfb-run npm run test:integration
```

2017-11-07 09:47 UTC, ronnyroeller commented
Thanks for the adjustments, @JaySunSyn 
Would you mind splitting the ESlint part into a separated PR (so we have the PR6 only cover the new feature without changing the build process)? Thanks.

2023-04-30 18:56 UTC, closed without merging